/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividadeativa;

/**
 *
 * @author Blue
 */
public class cadastroUniversidade extends javax.swing.JFrame {

    /**
     * Creates new form cadastroUniversidade
     */
    public cadastroUniversidade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCadastrar = new javax.swing.JLabel();
        btnCadastrarAluno = new javax.swing.JButton();
        btnCadastrarProfessor = new javax.swing.JButton();
        btnCadastrarProfssor = new javax.swing.JButton();
        lblConsultar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnConsultarCurso = new javax.swing.JButton();
        btnConsultarProfessor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelCadastrarAluno = new javax.swing.JPanel();
        panelCadastrarCurso = new javax.swing.JPanel();
        panelCadastrarProfessor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldNomeProfessor = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldTelefoneProfessor = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldTituloProfessor = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldAreaPesquisa = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldEndereçoProfessor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldNumeroEndereçoProfessor = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        fieldBairroProfessor = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        fieldCidadeProfessor = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        fieldCPFProfessor = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        fieldSalarioProfessor = new javax.swing.JFormattedTextField();
        btnFinalizarCadastroProfessor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCadastrar.setText("Cadastrar");

        btnCadastrarAluno.setText("Aluno");

        btnCadastrarProfessor.setText("Curso");

        btnCadastrarProfssor.setText("Professor");

        lblConsultar.setText("Consultar");

        jButton1.setText("Aluno");

        btnConsultarCurso.setText("Curso");

        btnConsultarProfessor.setText("Professor");

        jLabel1.setText("ESCOLHA AS AÇÕES DESEJADAS NOS BOTÕES");

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelCadastrarAlunoLayout = new javax.swing.GroupLayout(panelCadastrarAluno);
        panelCadastrarAluno.setLayout(panelCadastrarAlunoLayout);
        panelCadastrarAlunoLayout.setHorizontalGroup(
            panelCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        panelCadastrarAlunoLayout.setVerticalGroup(
            panelCadastrarAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        jLayeredPane1.add(panelCadastrarAluno, "card2");

        javax.swing.GroupLayout panelCadastrarCursoLayout = new javax.swing.GroupLayout(panelCadastrarCurso);
        panelCadastrarCurso.setLayout(panelCadastrarCursoLayout);
        panelCadastrarCursoLayout.setHorizontalGroup(
            panelCadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        panelCadastrarCursoLayout.setVerticalGroup(
            panelCadastrarCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        jLayeredPane1.add(panelCadastrarCurso, "card3");

        jLabel2.setText("CADASTRAR PROFESSOR");

        jLabel3.setText("NOME DO PROFESSOR");

        jLabel4.setText("Telefone");

        jLabel5.setText("Titulo");

        jLabel6.setText("Área de pesquisa");

        jLabel7.setText("Endereço");

        jLabel8.setText("Número");

        jLabel9.setText("Bairro");

        jLabel10.setText("Cidade");

        jLabel11.setText("CPF");

        jLabel12.setText("Salário");

        btnFinalizarCadastroProfessor.setText("Cadastrar");

        javax.swing.GroupLayout panelCadastrarProfessorLayout = new javax.swing.GroupLayout(panelCadastrarProfessor);
        panelCadastrarProfessor.setLayout(panelCadastrarProfessorLayout);
        panelCadastrarProfessorLayout.setHorizontalGroup(
            panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                        .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(fieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                        .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldSalarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5)
                                                .addComponent(fieldTituloProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldBairroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9)))
                                        .addGap(6, 6, 6)
                                        .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(fieldAreaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fieldCidadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fieldTelefoneProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4))
                                                .addGap(94, 94, 94))
                                            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel10)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
                    .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                        .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                                .addComponent(fieldEndereçoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(fieldNumeroEndereçoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(btnFinalizarCadastroProfessor)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelCadastrarProfessorLayout.setVerticalGroup(
            panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastrarProfessorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefoneProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTituloProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAreaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEndereçoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNumeroEndereçoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldBairroProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCidadeProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadastrarProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCPFProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSalarioProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnFinalizarCadastroProfessor)
                .addGap(34, 34, 34))
        );

        jLayeredPane1.add(panelCadastrarProfessor, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCadastrar)
                    .addComponent(btnCadastrarProfssor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCadastrarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsultarProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblConsultar)
                    .addComponent(btnConsultarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCadastrar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarAluno)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrarProfessor)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadastrarProfssor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(31, 31, 31))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultarProfessor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroUniversidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroUniversidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarAluno;
    private javax.swing.JButton btnCadastrarProfessor;
    private javax.swing.JButton btnCadastrarProfssor;
    private javax.swing.JButton btnConsultarCurso;
    private javax.swing.JButton btnConsultarProfessor;
    private javax.swing.JButton btnFinalizarCadastroProfessor;
    private javax.swing.JFormattedTextField fieldAreaPesquisa;
    private javax.swing.JFormattedTextField fieldBairroProfessor;
    private javax.swing.JFormattedTextField fieldCPFProfessor;
    private javax.swing.JFormattedTextField fieldCidadeProfessor;
    private javax.swing.JFormattedTextField fieldEndereçoProfessor;
    private javax.swing.JFormattedTextField fieldNomeProfessor;
    private javax.swing.JFormattedTextField fieldNumeroEndereçoProfessor;
    private javax.swing.JFormattedTextField fieldSalarioProfessor;
    private javax.swing.JFormattedTextField fieldTelefoneProfessor;
    private javax.swing.JFormattedTextField fieldTituloProfessor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblConsultar;
    private javax.swing.JPanel panelCadastrarAluno;
    private javax.swing.JPanel panelCadastrarCurso;
    private javax.swing.JPanel panelCadastrarProfessor;
    // End of variables declaration//GEN-END:variables
}
